version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: dataflow_postgres
    environment:
      POSTGRES_USER: cyril
      POSTGRES_PASSWORD: cyril
      POSTGRES_DB: dataflow_db
    ports:
      -  "5432:5432"
    volumes:
      - volume_db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U cyril"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  volume_db: